# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Anton Davydov
tagline:             Blog
description:         "Simple blog where I'll write about ruby, my ideas and technologies which I love<br><a href=\"https://twitter.com/anton_davydov\" target=\"_blank\">@anton_davydov</a>"
url:                 http://blog.davydovanton.com
paginate:            10

gems:
  - jemoji
  - jekyll-paginate

# About/contact
author:
  name:              Anton Davydov
  url:               https://davydovanton.com
  email:             antondavydov.o@gmail.com

# Conversion
markdown: kramdown

# Custom vars
version:             3.0.0
